### ISSUE TITLE
Characters per line feature

### ISSUE THREAD

**Issue by Leinad4Mind** [tophf/ijitsuki#1]
It could be added a new funcionality.

Characters per line: http://i.imgur.com/ZHdxUpf.png
So we could put 38 or 42 as maximum, and then Blame.moon would do the trick of marking them.

Best Regards

**Comment by tophf** [comment]
Oops sorry, I missed this post. Yeah, the idea is probably good, I just thought CPS (chars-per-second) is sufficient.

**Comment by tophf** [comment]
Closed via a5f3bc8c119d3666c518dccd6af0287e473e2b85
