### ISSUE TITLE
New Feature for Blame: detect lines with negative timing

### ISSUE THREAD

**Issue by Leinad4Mind** [tophf/ijitsuki#2]
It would be handy if Blame could detect lines with negative timing. That the end timing is inferior than the begining timing. Or when the begining timing is with the same timing as the end.

**Comment by tophf** [comment]
Yeah, good idea.

However aren't there better macros that detect more problems? Because if there are, I wonder whether it's worth enhancing Blame at all. Having not used Aegisub for a year or more I just don't know the state of affairs in the field...

**Comment by Leinad4Mind** [comment]
I'm not aware of nothing better then Blame. :p 
I guess nothing was created on macros. :/

**Comment by tophf** [comment]
Closed via a5f3bc8c119d3666c518dccd6af0287e473e2b85
